# Generated by Django 4.0 on 2022-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_crops_farmingtech'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='cropimg',
            field=models.TextField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.croptrust.org%2Fabout-us%2F&psig=AOvVaw1FZqITIQTLx14SxhLQIRDS&ust=1649005670360000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCIjl1Pvu9fYCFQAAAAAdAAAAABAD'),
        ),
        migrations.AddField(
            model_name='farmingtech',
            name='techimg',
            field=models.TextField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.alimentarium.org%2Fen%2Ffact-sheet%2Farable-farming-techniques&psig=AOvVaw38P2DborETGsZ23i8otB8i&ust=1649005701555000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKC0hYzv9fYCFQAAAAAdAAAAABAD'),
        ),
    ]
